# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
root = "."

# Test directory
testdata_dir = "testdata"

[build]
# Binary file name
bin = "./tmp/main"

# Binary build command
cmd = "go build -o ./tmp/main ./cmd/server"

# Watch these filename extensions
include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "json"]

# Ignore these filename extensions or directories
exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules", "bin"]

# Watch these directories if you specified
include_dir = []

# Exclude files
exclude_file = []

# Exclude regular expressions
exclude_regex = ["_test.go"]

# Exclude unchanged files
exclude_unchanged = false

# Follow symlinks
follow_symlink = false

# This log file places in your tmp_dir
log = "logs/errors.log"

# Poll files for changes instead of using fsnotify
poll = false

# Poll interval (ms)
poll_interval = 0

# It's not necessary to trigger build each time file changes if it's too frequent
delay = 1000

# Stop running old binary when build errors occur
stop_on_error = false

# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false

# Delay after sending Interrupt signal
kill_delay = "0s"

# Rerun binary or not
rerun = false

# Delay after each executions
rerun_delay = 500

# Add additional arguments when running binary (bin/main)
args_bin = []

[log]
# Show log time
time = false

# Only show main log (without request logs)
main_only = false

[color]
# Customize each part's color
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = false 