environment: staging

server:
  host: "0.0.0.0"
  port: "8080"

database:
  host: "staging-db.example.com"
  port: "5432"
  user: "postgres"
  password: "${DATABASE_PASSWORD}"
  name: "p4rsec_staging"
  ssl_mode: "require"
  max_open_conns: 20
  max_idle_conns: 10

redis:
  host: "staging-redis.example.com"
  port: "6379"
  password: "${REDIS_PASSWORD}"
  db: 0

logger:
  level: "info"

jwt:
  secret: "${JWT_SECRET}"
  expiration_time: "12h"
