environment: development

server:
  host: "0.0.0.0"
  port: "8080"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  name: "p4rsec"
  ssl_mode: "disable"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "1h"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

logger:
  level: "info"

jwt:
  secret: "your-secret-key-change-in-production"
  expiration_time: "24h"
