environment: production

server:
  host: "0.0.0.0"
  port: "8080"
  read_timeout: "60s"
  write_timeout: "60s"
  idle_timeout: "300s"

database:
  host: "${DATABASE_HOST}"
  port: "${DATABASE_PORT}"
  user: "${DATABASE_USER}"
  password: "${DATABASE_PASSWORD}"
  name: "${DATABASE_NAME}"
  ssl_mode: "require"
  max_open_conns: 50
  max_idle_conns: 25
  conn_max_lifetime: "2h"

redis:
  host: "${REDIS_HOST}"
  port: "${REDIS_PORT}"
  password: "${REDIS_PASSWORD}"
  db: 0

logger:
  level: "warn"

jwt:
  secret: "${JWT_SECRET}"
  expiration_time: "2h"
